// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV6aOftBK9vKud_elM_mj2GICUW6eO8ls',
    appId: '1:58927123029:web:fe9f166ba1cb2ed35762dc',
    messagingSenderId: '58927123029',
    projectId: 'testing-827ee',
    authDomain: 'testing-827ee.firebaseapp.com',
    storageBucket: 'testing-827ee.firebasestorage.app',
    measurementId: 'G-QFEJFXN2HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2MfSFSoBDEtU2DDryb_ygQUuTsoPUpPE',
    appId: '1:58927123029:android:538643fef021437e5762dc',
    messagingSenderId: '58927123029',
    projectId: 'testing-827ee',
    storageBucket: 'testing-827ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6vCTs3qRdJ6fUCtiTNpB108mZ7YvAgdU',
    appId: '1:58927123029:ios:d48c3ddf947fac765762dc',
    messagingSenderId: '58927123029',
    projectId: 'testing-827ee',
    storageBucket: 'testing-827ee.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );
}
